### ISSUE TITLE
Sheepscott Salinity

### ISSUE THREAD

**Issue by DrK-Lo** [DrK-Lo/EasternOysterEnvData#4]
I think we are going to go back out and sample the Sheepscott, but at a site closer to the bouys. So I want to revisit the data we have for there and see what the salinity is.

**Comment by thais-neu** [comment]
I plotted and calculated main metrics from salinity data for that spot closer to the buoys and added to a new entry in the github repo. For reference, I calculated metrics and plotted salinity data for the nearby site (ME_DR_HI_High, Damariscotta River). I updated the note in the map and changed the color of the pins from blue to green to indicate that we have temp and salinity for that location.

https://github.com/ModelValidationProgram/EasternOysterEnvData/blob/master/final_site_env/ME_potential_collection_site.md
